### PR TITLE
Use single quotes for file mode 

### PR DESCRIPTION
**Pull request by natewalck**
Makes the file mode consistent between the linux and darwin resources.

### CODE REVIEW

**Comment by tas50** [comment]
This is part of #219 as there's a cookstyle cop for stringifying modes

**Comment by nmcspadden** [comment]
This now has merge conflicts. @natewalck can you please fix the conflicts and rebase?

**Comment by nmcspadden** [comment]
@natewalck are you going to fix it?

**Comment by natewalck** [comment]
Eventually, yes.

**Comment by nmcspadden** [comment]
Feel free to re-open this when the conflicts are resolved.

**Pull request closed without merging**
