### PR TITLE
Add ubuntu support to node.console_user

### PR DESCRIPTION
**Pull request by natewalck**
astitled

### CODE REVIEW

**Comment by nmcspadden** [comment]
@natewalck is this still something you want to merge? Can you update it and recheck now that the CI config has been fixed?

**Comment by natewalck** [comment]
Hrmmm. I still see this rule firing: `FC066: Ensure chef_version is set in metadata:`

**Comment by natewalck** [comment]
Looks like none of the errors are related to this cookbook, so I say just land it ;)

**Comment by natewalck** [comment]
Also for reference, we've been using this for 1-2 months now.

**Comment by erikng** [comment]
We need to send an update for older Debian versions as well.

Thanks,
Erik Gomez
________________________________

**Pull request merged**
