### PR TITLE
Re-sync with internal repository

### PR DESCRIPTION
**Pull request by michel-slm**
The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

---
This change is [Reviewable](https://reviewable.io/reviews/facebook/it-cpe/230)

### CODE REVIEW

**Comment by michel-slm** [comment]
Accidentally pushed the old version of cpe_remote before the fixes for open sourcing

**Comment by erikng** [comment]
Looks like it's still missing some things.

**Comment by natewalck** [comment]
We are still missing this from the old cpe_remote_pkg: https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_remote/resources/pkg.rb#L24

**Comment by michel-slm** [comment]
@natewalck is there a pull request for it, or an issue filed?

**Comment by michel-slm** [comment]
@erikng @natewalck ah yes, #216 introduced `allow_downgrade` but it was never reapplied to our internal copy. Fix going out now!

**Pull request merged**
