### PR TITLE
Cookbook to blacklist PreferencePanes.

### PR DESCRIPTION
**Pull request by cgerke**
Pull? last one tonight...time for sleep.

### CODE REVIEW

**Comment by erikng** [comment]
I think in this case, you shouldn't use MC X, but rather the native method Apple provides via profiles. My internal preference pane cookbook uses `'PayloadType' => 'com.apple.systempreferences'`

**Comment by cgerke** [comment]
Np. I don't see "internal preference pane cookbook", or has it yet to be added?

**Comment by erikng** [comment]
I don't work for Facebook. Pinterest has one. :P


On Aug 18, 2016, at 4:17 PM, cgerke <notifications@github.com<mailto:notifications@github.com>> wrote:


Np. I don't see "internal preference pane cookbook", or has it yet to be added?

-

**Comment by cgerke** [comment]
Cool. You going to do a pull request to get it in here?

**Comment by erikng** [comment]
Nope. It won't be here.

Sent from my iPhone

On Aug 18, 2016, at 6:03 PM, cgerke <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool. You going to do a pull request to get it in here?

-

**Comment by cgerke** [comment]
ok np. will rewrite.

**Pull request closed without merging**
