### PR TITLE
replaces  with . Removes one duplicate assignment.

### PR DESCRIPTION
**Pull request by w0de**
Replaces `node['organization'] ? node['organization'] || 'Facebook'` with `node['organization'] || 'Facebook'`. Removes one duplicate assignment. 

https://travis-ci.org/facebook/IT-CPE/builds/407917459?utm_source=github_status&utm_medium=notification

### CODE REVIEW

**Comment by erikng** [comment]
I don't think this is a duplicate assignment. This is a guard to ensure there isn't a nil value by accident. While your OR statement will work, it is technically not a guard.

**Comment by w0de** [comment]
Thanks for feedback! 

The duplicate assignment is line [122](https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_chrome/resources/cpe_chrome.rb#L122) and [150](https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_chrome/resources/cpe_chrome.rb#L150) of cpe_chrome/resources/cpe_chrome.rb.

Wouldn't the ternary and the OR statement always evaluate to the same, given the same values for the rightside value (`Facebook`) and `node['organization']`? The ternary is just a verbose way of expressing `||` in this case.

```
2.5.1 :004 >  x = nil
 => nil
2.5.1 :005 > y = 'Facebook'
 => "Facebook"
2.5.1 :006 > x ? x : y
 => "Facebook"
2.5.1 :007 > x || y
 => "Facebook"
2.5.1 :008 > y = nil
 => nil
2.5.1 :009 > x ? x : y
 => nil
2.5.1 :010 > x || y
 => nil
2.5.1 :011 > x = 'Gusto'
 => "Gusto"
2.5.1 :012 > x ? x : y
 => "Gusto"
2.5.1 :013 > x || y
 => "Gusto"
```

**Comment by erikng** [comment]
In this particular case (strings) you are right that this code is functionally the same, however in other cases this will not be the case.

Ternary's evaluate the values and are expressed as a shortened if/else, whereas this is an or. While they are similar, my opinion is that the current methodology is safer and more accurate with what the author's expect the code to do.

**Comment by ChefAustin** [comment]
@erikng For my own knowledge, mind supplying example code of the case you're referencing? 

I'm failing to understand exactly what you're implying (not disputing, just would like to see the code to substantiate, what seems to be ☝️ , a contentious statement).

**Comment by natewalck** [comment]
Because `node` is *always* defined in the context of a chef run, if you try to access a key that doesn't exist, it will return nil:

```
[1] pry(main)> node = {}
=> {}
[2] pry(main)> node['doesnotexist']
=> nil
```

Of course, if node were not defined at all, we'd have more problems than this particular line (chef would not work).

With organization present:
```
[1] pry(main)> node = {}
=> {}
[2] pry(main)> node['organization'] = 'Blah Co'
=> "Blah Co"
[3] pry(main)> node['organization'] ? node['organization'] : 'Facebook'
=> "Blah Co"
[4] pry(main)> node['organization'] || 'Facebook'
=> "Blah Co"
```

Without:
```
[1] pry(main)> node = {}
=> {}
[2] pry(main)> node['organization'] ? node['organization'] : 'Facebook'
=> "Facebook"
[3] pry(main)> node['organization'] || 'Facebook'
=> "Facebook"
```

This is functionally identical and definitely cleaner. 

The duplicate code on the chrome part looks like a copy paste error (as the first declaration is in scope for the second usage).

As for the chrome change, did you confirm that chrome canary still functions as expected? I'd like to see that functionality tested even though it looks fine.

**Pull request closed without merging**
