### PR TITLE
Support for optional_installs in cpe_munki

### LINKED ISSUE #152: optional_installs support for munki
Since https://github.com/munki/munki/pull/837 was merged it might be nice to add optional_installs support into cpe_munki. The following diff works for me. 

A) would the fb team accept the PR?
B) should we wait until an official release of munki before merging into cpe_munki?

```diff
diff --git a/cookbooks/cpe_munki/attributes/default.rb b/cookbooks/cpe_munki/attributes/default.rb
index c2a2b35..dc43010 100644
--- a/cookbooks/cpe_munki/attributes/default.rb
+++ b/cookbooks/cpe_munki/attributes/default.rb
@@ -19,6 +19,7 @@ default['cpe_munki'] = {
 default['cpe_munki']['local'] = {
   'managed_installs' => [],
   'managed_uninstalls' => [],
+  'optional_installs' => [],
 }
 default['cpe_munki']['preferences'] = {
   'AppleSoftwareUpdatesOnly' => false,
diff --git a/cookbooks/cpe_munki/resources/cpe_munki_local.rb b/cookbooks/cpe_munki/resources/cpe_munki_local.rb
index bb46ee8..507a135 100644
--- a/cookbooks/cpe_munki/resources/cpe_munki_local.rb
+++ b/cookbooks/cpe_munki/resources/cpe_munki_local.rb
@@ -20,7 +20,8 @@ default_action :run
 
 action :run do
   locals_exist = node['cpe_munki']['local']['managed_installs'].any? ||
-                node['cpe_munki']['local']['managed_uninstalls'].any?
+                node['cpe_munki']['local']['managed_uninstalls'].any? ||
+                node['cpe_munki']['local']['optional_installs'].any?
 
   return unless locals_exist
   return unless ::File.exist?('/usr/local/munki/managedsoftwareupdate')
@@ -71,9 +72,13 @@ def gen_plist
   uninstalls = validate_install_array(
     node['cpe_munki']['local']['managed_uninstalls'],
   )
+  optional = validate_install_array(
+    node['cpe_munki']['local']['optional_installs'],
+  )
   plist_hash = {
     'managed_installs' => installs,
     'managed_uninstalls' => uninstalls,
+    'optional_installs' => optional,
   }
   ::Chef::Log.info("cpe_munki_local: Managed installs: #{installs}")
   Plist::Emit.dump(plist_hash) unless plist_hash.nil?
diff --git a/cookbooks/cpe_user_customizations/recipes/clayton.burlison.rb b/cookbooks/cpe_user_customizations/recipes/clayton.burlison.rb
index 2ab8a19..c41ec2d 100644
```

### PR DESCRIPTION
**Pull request by clburlison**
Fix #152

### CODE REVIEW

**Comment by natewalck** [comment]
Awesome, thanks! :) I think we'll merge after it hits a munki release. I don't want to confuse anyone until its ready to go. (Thanks for the note in the readme).

**Comment by mikedodge04** [comment]
ping

**Comment by clburlison** [comment]
No release of munki supports this change yet. v3.3.0 is currently going through RC cycles ATM. When that goes live I'll update the readme in this PR, until then I think we should continue waiting.

**Comment by clburlison** [comment]
Munki 3.3 has landed. I've updated the note in the README. This is ready for merging.

**Comment by erikng** [comment]
ping on this as well.

**Comment by natewalck** [comment]
LGTM.

**Pull request merged**
