### PR TITLE
Manage application execution path restrictions

### PR DESCRIPTION
**Pull request by cgerke**
...to stop non-admins downloading and running unapproved applications etc etc

### CODE REVIEW

**Comment by natewalck** [comment]
What happens when both a whitelist and blacklist are specified? Are these options mutually exclusive?

**Comment by erikng** [comment]
No they are not. You can have both.

**Comment by cgerke** [comment]
I use whitelist as a fail safe. You have to be careful with it because with it because if you start filling it out with explicit paths, then you have to specify every path that you want to be "safe"

**Comment by erikng** [comment]
Chris, the only reason I didn't open source my version of this (both have the same limitation) is you can only specify one node.default per attribute. It would be awesome if you could add to the whitelist/blacklist across node customizations.

**Comment by cgerke** [comment]
Not following you, you referring to the other restrictions that its possible to use such as Burning restrictions etc?

**Comment by erikng** [comment]
No, if you specify a list in your company_init, but then a different node has another list specified, it will only follow the last list. Ideally you could keep adding paths if needed and have a level of inheritance that goes down.

**Comment by cgerke** [comment]
Ahh gotcha.

**Comment by erikng** [comment]
Example:

Company_init white lists foo.app
Node_1 white lists bar.app
Result: bar.app is white listed

What would be awesome is both of them are white listed.

**Comment by cgerke** [comment]
Yeah might make less of a management overhead.

I've been doing things like this;

Blacklist
/Library/Caches
/Users
/tmp

Whitelist
/

To try and cut down on the amount of settings to actually apply in here. Then for anyone that might need to execute scripts from their homedir (developers) I whitelist a generic path.

~/Documents/Code

But thats not ideal for obvous reasons.

**Comment by erikng** [comment]
Really off topic, but this is why I ended up testing (and probably will implement) Santa over this, and manage Santa with chef.

**Comment by cgerke** [comment]
We ended up going with Bit9 (https://www.carbonblack.com/) so we can manage both Mac and PC so my profile may eventually fade out. But I am keeping it around because its handy.

**Comment by erikng** [comment]
Currently use Confer (which was just purchased by Bit9) but it's being used for osquery-like things.

**Comment by natewalck** [comment]
@erikng You can definitely do lists for this. You must append though as only hashes get deep merging. 

cpe_appaccess's attributes/default.rb:

node['cpe_appaccess']['blacklist'] = []

Company_init default.rb:
node.default['cpe_appaccess']['blacklist'] << 'foo.app'

Node_1 default.rb:
node.default['cpe_appaccess']['blacklist'] << 'bar.app'

Result: foo.app and bar.app are blacklisted.

We follow this pattern for a few API cookbooks, but you must be careful to append, otherwise as you said, it will blow away the original values.

**Comment by cgerke** [comment]
@erikng has a better one.

**Pull request closed without merging**
