### PR TITLE
Added cpe_preferencepanes. Thanks Erik

### PR DESCRIPTION
**Pull request by cgerke**
Managing all the system preference panes...

### CODE REVIEW

**Comment by erikng** [comment]
As we discussed on Slack, this version will run every time, regardless if someone has specified values. Please see my version on my github for the fix.

**Comment by cgerke** [comment]
Again...thanks!

**Comment by mikedodge04** [comment]
also needs to be a custom resource

**Comment by natewalck** [comment]
This needs to be refactored to be a custom resource as Mike said. He just landed the bluetooth rewrite, so it is a pretty solid example of what this looks like:

https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_bluetooth/resources/cpe_bluetooth.rb

**Comment by cgerke** [comment]
Changed to a custom resource. For now I am only using the DisabledPreferencePanes key as I was having mixed results with the added option HiddenPreferencePanes. The latter option isnt native, only mcx and compositing seems to mess with the profile. It only ever disables them. Will play with it more but I personally think DisabledPreferencePanes is a better choice anyway for troubleshooting purposes.

**Comment by natewalck** [comment]
I assume both Hidden and Disabled PreferencePanes were tested and confirmed working as expected?

**Comment by cgerke** [comment]
@natewalck both work as expected.

**Comment by natewalck** [comment]
Lovin' it.

**Pull request merged**
